// Auto-generated AI Research Feed data (EN/ZH)
const PAPER_DATA = {
  "weeks": [
    {
      "id": "day-2026-07-13",
      "title": "Today · July 13, 2026",
      "summary": "Daily digest of 20 AI papers, labs blogs, and essays — arXiv preprints plus DeepMind, Hugging Face, BAIR, Lil'Log, Interconnects, The Gradient, AWS ML, and Microsoft Research.",
      "summary_zh": "今日AI精选20篇：覆盖arXiv最新论文，以及DeepMind、Hugging Face、BAIR、Lil'Log、Interconnects、The Gradient、AWS ML、Microsoft Research等博客与长文。",
      "papers": [
        {
          "title": "PHINN-EEG: Topological Time-Series Analysis of Dream-State EEG -- Dynamic Betti Curves for Dream Content Classification and Topology-Conditioned Neural Signal Synthesis",
          "title_zh": "PHINN-EEG：梦境状态脑电的拓扑时序分析——动态Betti曲线用于梦内容分类与信号合成",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Applications",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09662",
          "tldr": "Current electroencephalography (EEG)-based dream detection relies on power spectral density (PSD) and statistical moment features, achieving a state-of-the-art area under the recei…",
          "tldr_zh": "用持续同调（滑动窗口Takens嵌入+Vietoris-Rips）从多通道EEG提取动态Betti曲线，目标AUC约0.82–0.90，并探索拓扑条件流匹配合成梦态脑电。",
          "summary": "Current electroencephalography (EEG)-based dream detection relies on power spectral density (PSD) and statistical moment features, achieving a state-of-the-art area under the receiver operating characteristic curve (AUC) of approximately 0.70 on the DREAM database (Wong et al., 2025, Nature Communications). We introduce PHINN-EEG (Persistent Homology Inspired Neural Network for EEG), the first topological time-series framework for dream mentation analysis. Using sliding-window Takens delay embeddings and Vietoris-Rips filtrations on multichannel pre-awakening EEG epochs, we extract Dynamic Bet…",
          "summary_zh": "现有基于PSD/统计矩的梦检测AUC约0.70。本文提出PHINN-EEG，将相位空间几何（而非仅频谱能量）用于梦境相关脑电分析，并给出拓扑条件整流流合成与Betti过渡原型假说，面向可穿戴BCI梦监测。"
        },
        {
          "title": "Scalable Visual Pretraining for Language Intelligence",
          "title_zh": "面向语言智能的可扩展视觉预训练",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Model Architecture",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09657",
          "tldr": "The rapid progress of large foundation models has been driven predominantly by pretraining on large-scale text corpora. However, many forms of knowledge are conveyed through visual…",
          "tldr_zh": "挑战“语言模型必须纯文本预训练”的默认假设：直接在视觉文档上做无监督视觉预训练，在相同语料下持续优于纯文本预训练。",
          "summary": "The rapid progress of large foundation models has been driven predominantly by pretraining on large-scale text corpora. However, many forms of knowledge are conveyed through visual representations, where figures, typeset equations, and page layouts carry rich information that cannot be faithfully or completely captured by text alone. Yet current pretraining approaches discard these visual cues by converting visually rich sources, such as documents and web pages, into plain text for learning language intelligence. This paper challenges the default assumption that language models must be trained…",
          "summary_zh": "图表、公式与版面承载了文本抽取无法完整保留的信息。作者系统研究多种无监督视觉预训练范式，在多种骨干与基准上证明：对同一语料直接用视觉表示预训练，可成为可扩展语言智能的有效路径。"
        },
        {
          "title": "Evolution of Accuracy and Visual-Cognitive Errors in a Decade of Vision-Language AI Models",
          "title_zh": "十年视觉-语言模型：准确率演进与视觉认知误差",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Model Architecture",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09654",
          "tldr": "Vision language models (VLMs) have made remarkable progress in visual reasoning during the last decade. Most evaluations have used simple scenes (MS-COCO) that do not showcase comp…",
          "tldr_zh": "回顾十年VLM发展，量化准确率提升轨迹，并系统刻画视觉认知类错误模式如何随模型迭代变化。",
          "summary": "Vision language models (VLMs) have made remarkable progress in visual reasoning during the last decade. Most evaluations have used simple scenes (MS-COCO) that do not showcase complex human interactions or behaviors, only a handful of non-curated human descriptions as a benchmark, and have not focused on understanding the model's error types. Here, we introduce the Complex Social Behavior (CSB) dataset, containing 100 images depicting complex social interactions/behaviors. We analyze the progression of scene descriptions over a decade (2017-2025) of VLMs (four pre-Multimodal Large Language Mod…",
          "summary_zh": "论文纵向比较多代视觉-语言模型，不仅报告分数增长，还剖析幻觉、属性绑定失败、空间推理等错误类型的演变，为下一阶段评测与训练目标提供实证依据。"
        },
        {
          "title": "VEXAIoT: Autonomous IoT Vulnerability EXploitation using AI Agents",
          "title_zh": "VEXAIoT：用AI智能体自主发现并利用物联网漏洞",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Safety & Alignment",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09653",
          "tldr": "Internet of Things (IoT) systems are inherently vulnerable due to constrained hardware, outdated firmware, and insecure default configurations, creating a need for scalable and ada…",
          "tldr_zh": "构建可自主探测与利用IoT漏洞的AI智能体系统，用于安全评估与红队场景。",
          "summary": "Internet of Things (IoT) systems are inherently vulnerable due to constrained hardware, outdated firmware, and insecure default configurations, creating a need for scalable and adaptive security testing approaches. While recent adoptions of Large Language Model (LLM) agents have demonstrated promise in penetration testing and Capture-the-Flag (CTF) environments, their application to IoT specific vulnerabilities remains unexplored. This paper presents an autonomous multi-agent framework, referred to as Vulnerability EXploitation using AI Agents (VEXAIoT), for vulnerability discovery and exploit…",
          "summary_zh": "面向物联网设备脆弱性，将规划、工具调用与漏洞利用链交给智能体自动化执行，强调可扩展的自主攻防评估能力，同时提示双重用途风险。"
        },
        {
          "title": "ConceptSMILE: Auditing the Trustworthiness of Concept-Based Explainable AI",
          "title_zh": "ConceptSMILE：审计基于概念的可解释AI可信度",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Interpretability",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09649",
          "tldr": "Concept-based explainable artificial intelligence (AI) can make model reasoning more human-understandable, but concept-level outputs are not automatically trustworthy. We introduce…",
          "tldr_zh": "提出针对概念解释（concept-based XAI）的可信度审计框架，检验解释是否稳定、忠实与可操作。",
          "summary": "Concept-based explainable artificial intelligence (AI) can make model reasoning more human-understandable, but concept-level outputs are not automatically trustworthy. We introduce ConceptSMILE, a model-agnostic perturbation-based auditing framework for evaluating the reliability of concept-based explanations. Rather than replacing SMILE, ConceptSMILE extends its perturbation-based logic from feature- or region-level attribution to the auditing of human-understandable concept explanations. The framework perturbs input regions, measures concept-response shifts, applies locality weighting, and f…",
          "summary_zh": "概念瓶颈/概念激活向量等方法流行，但其解释质量常缺乏系统审计。ConceptSMILE从忠实性、稳定性与决策相关度等维度评估概念解释，帮助发现虚假或脆弱的“可解释性”。"
        },
        {
          "title": "Deep Gaussian Processes on Directed Acyclic Graphs",
          "title_zh": "有向无环图上的深度高斯过程",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Model Architecture",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09645",
          "tldr": "Many real-world processes can be represented as compositions of functions along a directed acyclic graph (DAG). In causal modelling, these correspond to the underlying mechanisms; …",
          "tldr_zh": "将深度高斯过程扩展到DAG结构，以建模变量间的因果/层次依赖与不确定性。",
          "summary": "Many real-world processes can be represented as compositions of functions along a directed acyclic graph (DAG). In causal modelling, these correspond to the underlying mechanisms; in engineering, to multiple fidelity levels; and in gene-regulatory networks, to transcription factors. These functions are partially observed across the DAG, with noisy and heterogeneously sampled measurements, posing significant challenges for reconstruction, uncertainty propagation, and inference. To tackle these challenges, we place priors over functions and naturally arrive at Deep Gaussian Processes over DAGs. …",
          "summary_zh": "结合结构化依赖与非参数贝叶斯，研究在DAG上堆叠高斯过程层的推断与学习，适用于需要校准不确定性的结构化预测任务。"
        },
        {
          "title": "Semantic Pareto-DQN: A Multi-Objective Reinforcement Learning Framework for Financial Anomaly Detection",
          "title_zh": "Semantic Pareto-DQN：多目标强化学习方法",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Model Architecture",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09641",
          "tldr": "Financial anomaly detection suffers from extreme class imbalance, causing traditional single-objective algorithms to exhibit ``fraud collapse'', defaulting to the majority class an…",
          "tldr_zh": "在多目标强化学习中引入语义Pareto最优思想，平衡相互冲突的奖励目标。",
          "summary": "Financial anomaly detection suffers from extreme class imbalance, causing traditional single-objective algorithms to exhibit ``fraud collapse'', defaulting to the majority class and failing to balance anomaly interdiction with customer friction. To overcome this without distortive data resampling, we propose the Semantic Pareto-DQN, a multi-objective reinforcement learning framework. Our approach synthesizes heterogeneous transaction features into cohesive natural-language narratives, encoded by large language models, thereby producing a robust, scale-invariant state representation. The agent …",
          "summary_zh": "真实决策常有多个不可公度目标。该方法将Pareto前沿搜索与语义约束结合，提升多目标策略的可解释权衡与样本效率。"
        },
        {
          "title": "Lean-QIT: Towards a Formal Infrastructure for Quantum Information Theory",
          "title_zh": "Lean-QIT：面向量子信息理论的形式化基础设施",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Applications",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09632",
          "tldr": "Quantum information theory (QIT) characterizes the capabilities and fundamental limits of quantum information processing, underpinning quantum communication, computation, and error…",
          "tldr_zh": "在Lean中搭建量子信息理论形式化基础，推动可机器检查的量子证明与工具链。",
          "summary": "Quantum information theory (QIT) characterizes the capabilities and fundamental limits of quantum information processing, underpinning quantum communication, computation, and error correction. Formalizing its coding theorems requires connecting finite-block protocols, analytic inequalities, and asymptotic limits within a unified machine-checked framework. Existing developments, however, lack a reusable operational layer that defines codes, error criteria, achievable rates, and capacities independently of their information-theoretic characterizations. In this work, we present LeanQIT, a Lean 4 …",
          "summary_zh": "把量子信息核心定义与定理迁入交互式定理证明器，目标是降低形式化门槛、支持可复用库，服务安全关键协议与教学研究。"
        },
        {
          "title": "4DR360: State Reasoning for Joint 3D Detection and Occupancy Prediction in 4D Radar-Camera Full-Scene Perception",
          "title_zh": "4DR360：联合3D检测与占有的状态推理",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Systems & Optimization",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09629",
          "tldr": "Reliable autonomous driving requires full-scene perception that couples foreground objects with dense semantic layout. Recently, 4D millimeter-wave radar has emerged as a robust an…",
          "tldr_zh": "以状态推理统一三维目标检测与占据预测，提升动态场景理解。",
          "summary": "Reliable autonomous driving requires full-scene perception that couples foreground objects with dense semantic layout. Recently, 4D millimeter-wave radar has emerged as a robust and affordable sensor, yet its sparse returns make radar-camera fusion necessary for comprehensive scene understanding. Existing radar-camera methods mainly optimize detection, while dual-task systems usually decode boxes and occupancy with limited interaction. To address this gap and advance radar-based multi-task learning, we propose \\method, a 4D radar-camera framework for 360$^\\circ$ full-scene perception, which mo…",
          "summary_zh": "自动驾驶感知需同时给出物体与自由空间。4DR360强调时序状态与联合推理，改善遮挡与运动场景下的检测/占据一致性。"
        },
        {
          "title": "Task-Specific Multimodal Question Answering Agents via Confidence Calibration and Incremental Reasoning for QANTA 2026",
          "title_zh": "任务专用多模态问答智能体",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Systems & Optimization",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09623",
          "tldr": "We present our submission to the QANTA 2026 shared challenge at the ICML 2026 Workshop on Efficient Multimodal Question Answering (EMM-QA). Quanta evaluates multimodal quizbowl sys…",
          "tldr_zh": "通过任务特化构建多模态问答智能体，在垂直场景获得更高可靠性与效率。",
          "summary": "We present our submission to the QANTA 2026 shared challenge at the ICML 2026 Workshop on Efficient Multimodal Question Answering (EMM-QA). Quanta evaluates multimodal quizbowl systems that answer pyramid-style questions from incrementally revealed text and accompanying images while operating under realistic efficiency constraints. The challenge consists of two distinct tasks: Tossup questions, which require deciding when to answer under uncertainty, and Bonus questions, which emphasize accurate answer selection and human adoption. To address these differing objectives, we develop a task-speci…",
          "summary_zh": "通用多模态大模型在专业任务上常不稳定。本文讨论如何用工具、检索与任务数据把智能体收敛到特定问答工作流。"
        },
        {
          "title": "LLM for EDA in Front-End Design: Challenges and Opportunities",
          "title_zh": "前端设计中的EDA大模型：挑战与机遇",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Model Architecture",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09616",
          "tldr": "As chip complexity increases and time-to-market pressures grow, front-end design has become a critical bottleneck in chip development. Recently, Large Language Models (LLMs) have s…",
          "tldr_zh": "综述大语言模型在电子设计自动化前端（规范、RTL、验证等）的应用挑战与机会。",
          "summary": "As chip complexity increases and time-to-market pressures grow, front-end design has become a critical bottleneck in chip development. Recently, Large Language Models (LLMs) have shown great potential in Electronic Design Automation (EDA). Beyond specification understanding, LLMs show the potential to serve as a unified intelligent interface for hardware description language (HDL) generation, testbench construction, and design space exploration. The rise of agentic AI, represented by pioneering systems such as OpenClaw, offers a strategic roadmap for the next generation EDA. From this perspect…",
          "summary_zh": "EDA流程长、约束硬、正确性要求高。文章梳理LLM在规格理解、代码生成、调试辅助等环节的现状，并指出数据、评测与可验证性瓶颈。"
        },
        {
          "title": "Toward Real-Time Sentence-Level Sign Language Translation",
          "title_zh": "迈向实时句级手语翻译",
          "publisher": "arXiv",
          "date": "July 10, 2026",
          "category": "Model Architecture",
          "content_type": "paper",
          "url": "https://arxiv.org/abs/2607.09611",
          "tldr": "Most sign language understanding systems operate at the level of isolated signs, limiting their usefulness in natural communication. We study sentence-level sign language translati…",
          "tldr_zh": "研究低延迟、句级手语到文本/语音翻译，面向实时沟通场景。",
          "summary": "Most sign language understanding systems operate at the level of isolated signs, limiting their usefulness in natural communication. We study sentence-level sign language translation (SLT) with the primary goal of real-time deployment rather than proposing a new translation architecture. We fine-tune a SHuBERT-ByT5 translation stack on a uniformly sampled 9,872-example subset of How2Sign, selected because of compute and storage constraints, using QLoRA while keeping SHuBERT frozen. The model obtains a validation BLEU of 16.7 and, on the test split, BLEU 15.9 and BLEURT 44.7. The main contribut…",
          "summary_zh": "连续手语翻译需在准确率与延迟间折中。工作聚焦句级切分、流式推理与实时系统约束，推动无障碍沟通应用。"
        },
        {
          "title": "Google DeepMind and A24 announce first-of-its-kind research partnership",
          "title_zh": "DeepMind与A24宣布开创性的研究合作",
          "publisher": "Google DeepMind",
          "date": "July 03, 2026",
          "category": "Applications",
          "content_type": "blog",
          "url": "https://deepmind.google/blog/google-deepmind-and-a24-announce-first-of-its-kind-research-partnership/",
          "tldr": "Google DeepMind and A24 announce first-of-its-kind research partnership",
          "tldr_zh": "Google DeepMind与电影公司A24建立研究合作，探索AI与叙事/创意产业交叉前沿。",
          "summary": "Google DeepMind and A24 announce first-of-its-kind research partnership",
          "summary_zh": "实验室官方博客介绍与A24的合作框架，关注生成式AI如何参与影视创作流程，同时触及版权、安全与艺术家协作等问题。"
        },
        {
          "title": "Start building with Nano Banana 2 Lite and Gemini Omni Flash",
          "title_zh": "开始使用 Nano Banana 2 Lite 与 Gemini Omni Flash 构建",
          "publisher": "Google DeepMind",
          "date": "June 30, 2026",
          "category": "Applications",
          "content_type": "blog",
          "url": "https://deepmind.google/blog/start-building-with-nano-banana-2-lite-and-gemini-omni-flash/",
          "tldr": "Start building with Nano Banana 2 Lite and Gemini Omni Flash",
          "tldr_zh": "DeepMind开放/更新轻量多模态与快速Gemini变体，降低构建多模态应用门槛。",
          "summary": "Start building with Nano Banana 2 Lite and Gemini Omni Flash",
          "summary_zh": "面向开发者介绍 Nano Banana 2 Lite 与 Gemini Omni Flash 的能力边界、接入方式与适用场景，强调更快迭代与更低成本部署。"
        },
        {
          "title": "Profiling in PyTorch (Part 3): Attention is all you profile",
          "title_zh": "PyTorch性能分析（第三部分）：注意力机制 profiling",
          "publisher": "Hugging Face",
          "date": "July 10, 2026",
          "category": "Model Architecture",
          "content_type": "blog",
          "url": "https://huggingface.co/blog/torch-attention-profile",
          "tldr": "Profiling in PyTorch (Part 3): Attention is all you profile",
          "tldr_zh": "Hugging Face技术博文：深入剖析注意力实现的性能瓶颈与 profiling 方法。",
          "summary": "Profiling in PyTorch (Part 3): Attention is all you profile",
          "summary_zh": "系列第三篇聚焦Attention算子：如何用profiler定位内核耗时、内存与吞吐问题，并给出优化线索，服务训练/推理工程师。"
        },
        {
          "title": "Data for Agents",
          "title_zh": "智能体所需的数据",
          "publisher": "Hugging Face",
          "date": "July 08, 2026",
          "category": "Applications",
          "content_type": "blog",
          "url": "https://huggingface.co/blog/nvidia/open-data-for-agents",
          "tldr": "Data for Agents",
          "tldr_zh": "讨论训练与评测AI智能体需要什么样的数据、轨迹与环境日志。",
          "summary": "Data for Agents",
          "summary_zh": "智能体不仅靠静态语料，更依赖工具交互轨迹、失败恢复与长程任务数据。文章梳理数据形态、采集难点与开源生态机会。"
        },
        {
          "title": "Harness Engineering for Self-Improvement",
          "title_zh": "面向自我改进的Harness工程",
          "publisher": "Lil'Log",
          "date": "July 04, 2026",
          "category": "Interpretability",
          "content_type": "essay",
          "url": "https://lilianweng.github.io/posts/2026-07-04-harness/",
          "tldr": "The concept of recursive self-improvement (RSI) dates back to I. J. Good (1965) , where he defined an “ultraintelligent machine” as a system that can surpass humans in all intellec…",
          "tldr_zh": "Lilian Weng长文：如何设计让模型/智能体自我改进的训练与评估“挽具”（harness）。",
          "summary": "The concept of recursive self-improvement (RSI) dates back to I. J. Good (1965) , where he defined an “ultraintelligent machine” as a system that can surpass humans in all intellectual activities and design better machines to improve itself. Yudkowsky (2008) used the phrase “recursive self-improvement” for a specific feedback loop: an AI uses its current intelligence to improve the cognitive machinery that produces its intelligence. This feedback loop in modern AI may indicate the model rewriting its own weights directly, or more broadly the model improves the training pipeline and the deploym…",
          "summary_zh": "从反馈回路、评测脚手架到迭代训练管线，系统讨论自我改进系统的工程要素与失效模式，是偏研究随笔的深度综述。"
        },
        {
          "title": "Scaling Laws, Carefully",
          "title_zh": "谨慎地谈缩放律",
          "publisher": "Lil'Log",
          "date": "June 24, 2026",
          "category": "Model Architecture",
          "content_type": "essay",
          "url": "https://lilianweng.github.io/posts/2026-06-24-scaling-laws/",
          "tldr": "Scaling laws are one of the most critical empirical findings in deep learning. The observation is simple in form: the training loss $L$ decreases predictably as we scale up model s…",
          "tldr_zh": "对缩放律结论做审慎解读：适用边界、测量噪声与过度外推风险。",
          "summary": "Scaling laws are one of the most critical empirical findings in deep learning. The observation is simple in form: the training loss $L$ decreases predictably as we scale up model size $N$, dataset size $D$, and compute $C$, following a power-law curve, which appears as a straight line on a log-log plot. We can view scaling laws as a framework for describing the relationship between compute, loss, model size and data; at its core, it is about how to allocate precious compute optimally between $N$ and $D$.",
          "summary_zh": "缩放律很有用，但常被简化为口号。文章提醒数据质量、算力配比、下游迁移等条件，主张更严格的实验报告与外推纪律。"
        },
        {
          "title": "6 months to live for open models",
          "title_zh": "开源模型只剩六个月寿命？",
          "publisher": "Interconnects",
          "date": "July 12, 2026",
          "category": "Model Architecture",
          "content_type": "essay",
          "url": "https://www.interconnects.ai/p/6-months-to-live-for-open-models",
          "tldr": "The most serious test to date of open source AI’s viability is happening right now.",
          "tldr_zh": "Interconnects评论：开源权重模型的竞争半衰期与生态策略。",
          "summary": "The most serious test to date of open source AI’s viability is happening right now.",
          "summary_zh": "围绕开源模型发布节奏、闭源追赶与社区复现，讨论“窗口期”叙事是否成立，以及对创业与研究选型的含义。"
        },
        {
          "title": "Latest open artifacts (#22): Zyphra, Cohere, and Poolside are expanding the breadth of the ecosystem",
          "title_zh": "最新开源产物（#22）：Zyphra、Cohere 与 Poolside",
          "publisher": "Interconnects",
          "date": "June 28, 2026",
          "category": "Model Architecture",
          "content_type": "essay",
          "url": "https://www.interconnects.ai/p/artifacts-22-zyphra-cohere-and-poolside",
          "tldr": "An assessment of the open ecosystem and the motivations behind releasing models",
          "tldr_zh": "开源模型/数据集/工具动态速览：Zyphra、Cohere、Poolside 等最新发布。",
          "summary": "An assessment of the open ecosystem and the motivations behind releasing models",
          "summary_zh": "行业通讯式长文，汇总近期开源权重、推理栈与训练产物，方便快速跟进多厂商开源动态。"
        }
      ]
    }
  ]
};
